workflows:
  local:
    node-project:
      setup-standard:
        dependencies:
          - '@liquid-labs/catalyst-resource-babel-and-rollup'
          - '@liquid-labs/catalyst-resource-eslint'
          - '@liquid-labs/catalyst-resource-jest'
        scripts:
          - builder: '@liquid-labs/catalyst-lib-makefiles'
            version: 1.0.0-alpha.3
            priority: 0
            path: Makefile
            purpose: >-
              Sets up standard target vars (like 'BUILD_TARGETS') and runs
              scripts from 'make'.
          - builder: '@liquid-labs/catalyst-lib-makefiles'
            version: 1.0.0-alpha.3
            priority: 10
            path: make/10-locations.mk
            purpose: Defines the most basic locations, like the source directory.
          - builder: '@liquid-labs/catalyst-builder-node'
            version: 1.0.0-alpha.0
            priority: 10
            path: make/10-resources.mk
            purpose: Locates tool executables and configuration files.
          - builder: '@liquid-labs/catalyst-builder-node'
            version: 1.0.0-alpha.0
            priority: 15
            path: make/15-data-finder.mk
            purpose: >-
              Sets up vars listing test data files which will need to be copied
              under the test staging dir.
          - builder: '@liquid-labs/catalyst-builder-node'
            version: 1.0.0-alpha.0
            priority: 20
            path: make/20-js-src-finder.mk
            purpose: >-
              Sets up vars listing JS files which will need to be tested and
              built.
          - builder: '@liquid-labs/catalyst-builder-node'
            version: 1.0.0-alpha.0
            priority: 50
            path: make/50-catalyst-server-js.mk
            purpose: Builds the 'dist/catalyst-server.js' artifact.
          - builder: '@liquid-labs/catalyst-builder-node'
            version: 1.0.0-alpha.0
            priority: 50
            path: make/50-catalyst-server-exec-js.mk
            purpose: Builds the 'dist/catalyst-server-exec.js' artifact.
          - builder: '@liquid-labs/catalyst-builder-node'
            version: 1.0.0-alpha.0
            priority: 55
            path: make/55-lint.mk
            purpose: Provides lint functionality with eslint.
          - builder: '@liquid-labs/catalyst-builder-node'
            version: 1.0.0-alpha.0
            priority: 55
            path: make/55-test.mk
            purpose: Provides test functionality with jest.
          - builder: '@liquid-labs/catalyst-lib-makefiles'
            version: 1.0.0-alpha.3
            priority: 95
            path: make/95-final-targets.mk
            purpose: >-
              Sets up the final basic targets (like 'build') based on the target
              vars (like 'BUILD_TARGETS').
        config:
          noDevInstall: true
          noDoc: true
