# This file was generated by @liquid-labs/catalyst-lib-makefiles. Refer to
# https://npmjs.com/package/@liquid-labs/catalyst-lib-makefiles for furtehr
# details

.DELETE_ON_ERROR:

SHELL:=bash

BUILD_TARGETS:=

DOC_TARGETS:=

LINT_TARGETS:=

TEST_TARGETS:=

ifneq ($(wildcard make/*.mk),)
include make/*.mk
endif
