# This file was generated by @liquid-labs/catalyst-lib-makefiles. Refer to
# https://npmjs.com/package/@liquid-labs/catalyst-lib-makefiles for further
# details

SRC:=src
DIST:=dist
TEST_STAGING:=test-staging
QA:=qa
