# This file was generated by @liquid-labs/catalyst-builder-node. Refer to
# https://npmjs.com/package/@liquid-labs/catalyst-builder-node for furtehr details

SRC:=src
DIST:=dist
TEST_STAGING:=test-staging
QA:=qa
