# This file was generated by @liquid-labs/sdlc-projects-workflow-local-node-build.
# Refer to https://npmjs.com/package/@liquid-labs/sdlc-projects-workflow-local-
# node-build for further details

#####
# build dist/dev-core.js
#####

SDLC_DEV_CORE_JS:=$(DIST)/dev-core.js
SDLC_DEV_CORE_JS_ENTRY=$(SRC)/index.mjs
BUILD_TARGETS+=$(SDLC_DEV_CORE_JS)

$(SDLC_DEV_CORE_JS): package.json $(SDLC_ALL_NON_TEST_JS_FILES_SRC)
	JS_BUILD_TARGET=$(SDLC_DEV_CORE_JS_ENTRY) \
	  JS_OUT=$@ \
	  $(SDLC_ROLLUP) --config $(SDLC_ROLLUP_CONFIG)

#####
# end dist/dev-core.js
#####
