# make/55-test-filter-guard.mk -- hand-authored, not Catalyst-generated. Every other
# 'make/*.mk' fragment this repository lists in '.catalyst-data.yaml' carries a "generated by
# @liquid-labs/catalyst-*" banner; this one carries neither, and is not listed there, so a
# future Catalyst regeneration pass leaves it alone (mirrors make/56-plugin-graph.mk's own
# rationale for the same thing).
#
# make/55-test.mk's pass marker ($(CATALYST_TEST_PASS_MARKER)) is keyed purely on file mtimes --
# it has no notion of the '$(TEST)' jest-filter argument 'make/55-test.mk' passes straight
# through to jest. Running `TEST=<pattern> make test` touches that same marker file that a later
# *unfiltered* `make test` checks against, so the unfiltered run sees the marker up to date and
# reports "Nothing to be done", exiting 0 without ever running the full suite -- a filtered green
# run masquerading as a full one.
#
# Fix: record the '$(TEST)' value that produced the current pass marker in a small state file,
# and blow away the (possibly stale) pass marker whenever the recorded value disagrees with the
# current one, before make decides whether the marker needs rebuilding. This file's own name is
# deliberately picked to sort ahead of 'make/55-test.mk' in wildcard-include order -- '-' (0x2D)
# sorts before '.' (0x2E), so "55-test-filter-guard.mk" < "55-test.mk" -- which appends this
# guard's own target to $(TEST_TARGETS) *before* make/55-test.mk appends the pass marker, and
# therefore runs the guard first in 'test: $(TEST_TARGETS)"'s (make/95-final-targets.mk)
# left-to-right prerequisite order.
#
# The guard target itself must stay PHONY: the thing it tracks ('$(TEST)') is a make variable,
# not a file, so there is no real prerequisite make's mtime-based staleness check could key off
# of -- checking on every invocation and only touching the state file when the value actually
# changed is the standard way to bridge that gap without falsely marking the *pass marker* itself
# phony (it still only rebuilds when genuinely stale).
CATALYST_TEST_FILTER_STATE:=$(QA)/.unit-test.filter
TEST_TARGETS+=$(CATALYST_TEST_FILTER_STATE)

.PHONY: $(CATALYST_TEST_FILTER_STATE)
$(CATALYST_TEST_FILTER_STATE):
	@mkdir -p $(dir $@)
	@current='$(TEST)'; \
	stored=''; \
	[ -f $@ ] && stored="$$(cat $@)"; \
	if [ "$$stored" != "$$current" ]; then \
	  rm -f $(CATALYST_TEST_PASS_MARKER); \
	  printf '%s' "$$current" > $@; \
	fi
