# make/56-plugin-graph.mk -- hand-authored, not Catalyst-generated. Every other 'make/*.mk'
# fragment in this repository carries a "generated by @liquid-labs/catalyst-*" banner; this one
# does not, and must not, or a future Catalyst regeneration pass will read it as stale output and
# remove it.
#
# Wires the compile-time plugin-manifest gate (`@liquid-labs/plugable-express`'s
# `validatePluginSet()`) into 'make test'/'make qa' so a broken declaration in this host's own
# `plugable.host` block (or a third-party manifest it depends on) fails the build here, not only
# in a downstream consumer's CI. See 'plan/notes/build-wiring-and-dependency-refresh.md' (this
# plan's own recipe) and the upstream precedent this mirrors,
# '/Users/zane/playground/liquid-labs/plugable-express/make/56-plugin-graph.mk'.
#
# TEST_TARGETS, not BUILD_TARGETS: 'make/95-final-targets.mk' defines 'qa: test lint', so
# appending to TEST_TARGETS reaches both 'make test' and 'make qa' with one line and no edit to
# any Catalyst-generated fragment.
#
# No dependency on 'dist/': the gate reads 'node_modules' and 'package.json', both present
# immediately after install. A broken plugin graph must be discoverable before a build is even
# attempted, not only after one succeeds.
#
# The gate itself is not driven through this recipe directly -- it is exercised by a dedicated
# Jest test, 'src/lib/test/plugin-graph-gate.test.js', which calls the exported
# `validatePluginSet()` directly against this repo's real package root. That test is one of the
# '*.test.js' files the generic Jest run (make/55-test.mk's $(CATALYST_TEST_PASS_MARKER)) already
# covers, so this marker only needs to depend on that shared pass marker rather than re-invoking
# Jest a second time -- "the Jest test itself is the gate; the marker is bookkeeping," the same
# shape the upstream fragment above uses.
#
# '56' is deliberate: it sits in the numbering gap between the '55-*' fragments and
# '95-final-targets.mk', so 'include make/*.mk' (Makefile) picks it up with no edit to a
# generated file or to Makefile itself. $(QA) is already defined by make/10-locations.mk.
CATALYST_PLUGIN_GRAPH_MARKER:=$(QA)/.plugin-graph.passed
TEST_TARGETS+=$(CATALYST_PLUGIN_GRAPH_MARKER)

$(CATALYST_PLUGIN_GRAPH_MARKER): $(CATALYST_TEST_PASS_MARKER)
	@mkdir -p $(dir $@)
	@touch $@
